repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
        -   id: check-docstring-first
        -   id: trailing-whitespace
        -   id: check-yaml
        -   id: sort-simple-yaml
        -   id: end-of-file-fixer
        -   id: pretty-format-json
        -   id: requirements-txt-fixer
        -   id: check-merge-conflict
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
