
secrets:
  database_password:
    file : ./configs/secrets/database_password.txt
services:
  library:
    build: .
    command: python library/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/library
    ports:
      - "8000:8000"
    depends_on: 
      db:
        condition: service_healthy
    secrets:
      - database_password
    environment:
      DATABASE_NAME: postgres
      DATABASE_USER: root
      DATABASE_PASSWORD_FILE: /run/secrets/database_password
      DATABASE_HOST: db
      DATABASE_PORT: 5432
  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD_FILE: /run/secrets/database_password
    ports:
      - "5432:5432"
    volumes:
      - dev-db:/var/lib/postgresql/data
    secrets:
      - database_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  dev-db:
